# .github/workflows/deploy.yml
name: Run Node App

on:
  push:   # triggers when you push code
    branches:
      - main

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run index.js with secret
        env:
          TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
        run: node index.js
